<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OddsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('odds')->insert([
            [
                'id' => 1,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578084,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 02:30:00',
                'home' => 'Rayo Vallecano',
                'away' => 'Celta Vigo',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.75,
                'money_line_a' => 2.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 2,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578062,
                'league_id' => 2436,
                'league_name' => 'Italy - Serie A',
                'starts' => '2023-12-12 00:00:00',
                'home' => 'Empoli',
                'away' => 'Lecce',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.71,
                'money_line_a' => 2.89,
                'money_line_d' => 3.14,
                'spreads_p' => 0,
                'spreads_h' => 1.892,
                'spreads_a' => 2.02,
                'totals_point' => 2.25,
                'over' => 1.925,
                'under' => 1.961,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 3,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578061,
                'league_id' => 2436,
                'league_name' => 'Italy - Serie A',
                'starts' => '2023-12-12 00:00:00',
                'home' => 'Bologna',
                'away' => 'AC Milan',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 4.1,
                'money_line_a' => 1.84,
                'money_line_d' => 3.62,
                'spreads_p' => 0,
                'spreads_h' => 1.925,
                'spreads_a' => 1.925,
                'totals_point' => 2.75,
                'over' => 1.925,
                'under' => 1.925,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 4,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578060,
                'league_id' => 2436,
                'league_name' => 'Italy - Serie A',
                'starts' => '2023-12-12 00:00:00',
                'home' => 'Atalanta',
                'away' => 'Udinese',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 1.4,
                'money_line_a' => 7.2,
                'money_line_d' => 4.7,
                'spreads_p' => 0,
                'spreads_h' => 1.925,
                'spreads_a' => 1.925,
                'totals_point' => 3.25,
                'over' => 1.925,
                'under' => 1.925,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
            'id' => 5,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578064,
            'league_id' => 2438,
            'league_name' => 'Germany - Bundesliga',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Bayern Munich',
            'away' => 'Borussia Dortmund',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
        ],
// ... Repeat this structure 9 more times with different data
        [
        'id' => 6,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578065,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Bayer Leverkusen',
        'away' => 'RB Leipzig',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 2.75,
        'money_line_a' => 2.71,
        'money_line_d' => 3.32,
        'spreads_p' => 0,
        'spreads_h' => 1.961,
        'spreads_a' => 1.934,
        'totals_point' => 2.5,
        'over' => 2.08,
        'under' => 1.826,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 7,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578066,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Borussia Monchengladbach',
        'away' => 'Eintracht Frankfurt',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 1.65,
        'money_line_a' => 4.85,
        'money_line_d' => 3.70,
        'spreads_p' => 0,
        'spreads_h' => 1.950,
        'spreads_a' => 1.950,
        'totals_point' => 3.5,
        'over' => 2.00,
        'under' => 1.850,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 8,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578067,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Freiburg',
        'away' => 'Hoffenheim',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 2.75,
        'money_line_a' => 2.71,
        'money_line_d' => 3.32,
        'spreads_p' => 0,
        'spreads_h' => 1.961,
        'spreads_a' => 1.934,
        'totals_point' => 2.5,
        'over' => 2.08,
        'under' => 1.826,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
            'id' => 9,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578068,
            'league_id' => 2438,
            'league_name' => 'Germany - Bundesliga',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Hertha Berlin',
            'away' => 'Mainz',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
        ],
        [
        'id' => 10,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578069,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Paderborn',
        'away' => 'Werder Bremen',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 2.75,
        'money_line_a' => 2.71,
        'money_line_d' => 3.32,
        'spreads_p' => 0,
        'spreads_h' => 1.961,
        'spreads_a' => 1.934,
        'totals_point' => 2.5,
        'over' => 2.08,
        'under' => 1.826,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 11,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578070,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Schalke',
        'away' => 'Augsburg',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 1.65,
        'money_line_a' => 4.85,
        'money_line_d' => 3.70,
        'spreads_p' => 0,
        'spreads_h' => 1.950,
        'spreads_a' => 1.950,
        'totals_point' => 3.5,
        'over' => 2.00,
        'under' => 1.850,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 12,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578071,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Wolfsburg',
        'away' => 'Hannover',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 2.75,
        'money_line_a' => 2.71,
        'money_line_d' => 3.32,
        'spreads_p' => 0,
        'spreads_h' => 1.961,
        'spreads_a' => 1.934,
        'totals_point' => 2.5,
        'over' => 2.08,
        'under' => 1.826,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 13,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578072,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Wolfsburg',
        'away' => 'Hannover',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 1.65,
        'money_line_a' => 4.85,
        'money_line_d' => 3.70,
        'spreads_p' => 0,
        'spreads_h' => 1.950,
        'spreads_a' => 1.950,
        'totals_point' => 3.5,
        'over' => 2.00,
        'under' => 1.850,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        [
        'id' => 14,
        'sport_id' => '1',
        'sport_name' => 'Soccer',
        'last_call' => '2023-12-11 08:10:01',
        'event_id' => 1582578073,
        'league_id' => 2438,
        'league_name' => 'Germany - Bundesliga',
        'starts' => '2023-12-12 01:30:00',
        'home' => 'Wolfsburg a',
        'away' => 'Hannover b',
        'event_type' => 'prematch',
        'is_have_odds' => 1,
        'money_line_h' => 2.75,
        'money_line_a' => 2.71,
        'money_line_d' => 3.32,
        'spreads_p' => 0,
        'spreads_h' => 1.961,
        'spreads_a' => 1.934,
        'totals_point' => 2.5,
        'over' => 2.08,
        'under' => 1.826,
        'created_at' => '2023-12-11 08:10:07',
        'updated_at' => '2023-12-11 08:10:07',
        'status' => 1
        ],
        // english premier league 40 teams
        [
            'id' => 15,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578074,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Arsenal',
            'away' => 'Aston Villa',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
            'id' => 16,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578075,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Bournemouth',
            'away' => 'Brighton',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 2.75,
            'money_line_a' => 2.71,
            'money_line_d' => 3.32,
            'spreads_p' => 0,
            'spreads_h' => 1.961,
            'spreads_a' => 1.934,
            'totals_point' => 2.5,
            'over' => 2.08,
            'under' => 1.826,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
            'id' => 17,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578076,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Burnley',
            'away' => 'Chelsea',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
            'id' => 18,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578077,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Crystal Palace',
            'away' => 'Everton',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 2.75,
            'money_line_a' => 2.71,
            'money_line_d' => 3.32,
            'spreads_p' => 0,
            'spreads_h' => 1.961,
            'spreads_a' => 1.934,
            'totals_point' => 2.5,
            'over' => 2.08,
            'under' => 1.826,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
           // 10 teams
            [
            'id' => 19,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578078,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Leicester',
            'away' => 'Liverpool',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
            'id' => 20,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578079,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Manchester City',
            'away' => 'Manchester United',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 2.75,
            'money_line_a' => 2.71,
            'money_line_d' => 3.32,
            'spreads_p' => 0,
            'spreads_h' => 1.961,
            'spreads_a' => 1,
            'totals_point' => 2.5,
            'over' => 2.08,
            'under' => 1.826,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            //  generate 10 teams
            [
            'id' => 21,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578080,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Newcastle',
            'away' => 'Norwich City',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 1.65,
            'money_line_a' => 4.85,
            'money_line_d' => 3.70,
            'spreads_p' => 0,
            'spreads_h' => 1.950,
            'spreads_a' => 1.950,
            'totals_point' => 3.5,
            'over' => 2.00,
            'under' => 1.850,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
            'id' => 22,
            'sport_id' => '1',
            'sport_name' => 'Soccer',
            'last_call' => '2023-12-11 08:10:01',
            'event_id' => 1582578081,
            'league_id' => 2438,
            'league_name' => 'England - Premier League',
            'starts' => '2023-12-12 01:30:00',
            'home' => 'Sheffield United',
            'away' => 'Southampton',
            'event_type' => 'prematch',
            'is_have_odds' => 1,
            'money_line_h' => 2.75,
            'money_line_a' => 2.71,
            'money_line_d' => 3.32,
            'spreads_p' => 0,
            'spreads_h' => 1.961,
            'spreads_a' => 1.934,
            'totals_point' => 2.5,
            'over' => 2.08,
            'under' => 1.826,
            'created_at' => '2023-12-11 08:10:07',
            'updated_at' => '2023-12-11 08:10:07',
            'status' => 1
            ],
            [
                'id' => 23,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578084,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 02:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.75,
                'money_line_a' => 2.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 25,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578085,
                'league_id' => 2197,
                'league_name' => 'France - Ligue 1',
                'starts' => '2023-12-12 02:45:00',
                'home' => 'Paris Saint-Germain',
                'away' => 'Lyon',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 1.75,
                'money_line_a' => 4.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 26,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578095,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:00:00',
                'home' => 'Atletico Madrid',
                'away' => 'Sevilla',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.15,
                'money_line_a' => 3.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 27,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578096,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:00:00',
                'home' => 'Valencia',
                'away' => 'Real Sociedad',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.15,
                'money_line_a' => 3.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

            [
                'id' => 28,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578097,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:00:00',
                'home' => 'Villarreal',
                'away' => 'Real Betis',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.15,
                'money_line_a' => 3.71,
                'money_line_d' => 3.32,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 29,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578105,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Valencia',
                'away' => 'Villarreal',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            [
                'id' => 30,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578106,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Villarreal',
                'away' => 'Real Betis a',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

            [
                'id' => 31,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578107,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona a',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

            // add champious league 10 teams
            [
                'id' => 32,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578108,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona a',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

            [
                'id' => 33,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578109,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona a',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            // ... Repeat this structure 9 more times with different data for champious league
            [
                'id' => 34,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578110,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona a',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],
            // add more
            [
                'id' => 35,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578111,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona b',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

            [
                'id' => 36,
                'sport_id' => '1',
                'sport_name' => 'Soccer',
                'last_call' => '2023-12-11 08:10:01',
                'event_id' => 1582578112,
                'league_id' => 2196,
                'league_name' => 'Spain - La Liga',
                'starts' => '2023-12-12 03:30:00',
                'home' => 'Real Madrid',
                'away' => 'Barcelona c',
                'event_type' => 'prematch',
                'is_have_odds' => 1,
                'money_line_h' => 2.55,
                'money_line_a' => 2.91,
                'money_line_d' => 3.22,
                'spreads_p' => 0,
                'spreads_h' => 1.961,
                'spreads_a' => 1.934,
                'totals_point' => 2.5,
                'over' => 2.08,
                'under' => 1.826,
                'created_at' => '2023-12-11 08:10:07',
                'updated_at' => '2023-12-11 08:10:07',
                'status' => 1
            ],

                [
                    'id' => 37,
                    'sport_id' => '1',
                    'sport_name' => 'Soccer',
                    'last_call' => '2023-12-11 08:10:01',
                    'event_id' => 1582578113,
                    'league_id' => 2196,
                    'league_name' => 'Spain - La Liga',
                    'starts' => '2023-12-12 03:30:00',
                    'home' => 'Real Madrid',
                    'away' => 'Barcelona d',
                    'event_type' => 'prematch',
                    'is_have_odds' => 1,
                    'money_line_h' => 2.55,
                    'money_line_a' => 2.91,
                    'money_line_d' => 3.22,
                    'spreads_p' => 0,
                    'spreads_h' => 1.961,
                    'spreads_a' => 1.934,
                    'totals_point' => 2.5,
                    'over' => 2.08,
                    'under' => 1.826,
                    'created_at' => '2023-12-11 08:10:07',
                    'updated_at' => '2023-12-11 08:10:07',
                    'status' => 1

                ],

                [
                    'id' => 38,
                    'sport_id' => '1',
                    'sport_name' => 'Soccer',
                    'last_call' => '2023-12-11 08:10:01',
                    'event_id' => 1582578114,
                    'league_id' => 2196,
                    'league_name' => 'Spain - La Liga',
                    'starts' => '2023-12-12 03:30:00',
                    'home' => 'Real Madrid',
                    'away' => 'Barcelona e',
                    'event_type' => 'prematch',
                    'is_have_odds' => 1,
                    'money_line_h' => 2.55,
                    'money_line_a' => 2.91,
                    'money_line_d' => 3.22,
                    'spreads_p' => 0,
                    'spreads_h' => 1.961,
                    'spreads_a' => 1.934,
                    'totals_point' => 2.5,
                    'over' => 2.08,
                    'under' => 1.826,
                    'created_at' => '2023-12-11 08:10:07',
                    'updated_at' => '2023-12-11 08:10:07',
                    'status' => 1
                ],
                    [
                        'id' => 39,
                        'sport_id' => '1',
                        'sport_name' => 'Soccer',
                        'last_call' => '2023-12-11 08:10:01',
                        'event_id' => 1582578115,
                        'league_id' => 2196,
                        'league_name' => 'Spain - La Liga',
                        'starts' => '2023-12-12 03:30:00',
                        'home' => 'Real Madrid',
                        'away' => 'Barcelona f',
                        'event_type' => 'prematch',
                        'is_have_odds' => 1,
                        'money_line_h' => 2.55,
                        'money_line_a' => 2.91,
                        'money_line_d' => 3.22,
                        'spreads_p' => 0,
                        'spreads_h' => 1.961,
                        'spreads_a' => 1.934,
                        'totals_point' => 2.5,
                        'over' => 2.08,
                        'under' => 1.826,
                        'created_at' => '2023-12-11 08:10:07',
                        'updated_at' => '2023-12-11 08:10:07',
                        'status' => 1
                    ],

                    [
                        'id' => 40,
                        'sport_id' => '1',
                        'sport_name' => 'Soccer',
                        'last_call' => '2023-12-11 08:10:01',
                        'event_id' => 1582578116,
                        'league_id' => 2196,
                        'league_name' => 'Spain - La Liga',
                        'starts' => '2023-12-12 03:30:00',
                        'home' => 'Real Madrid',
                        'away' => 'Barcelona g',
                        'event_type' => 'prematch',
                        'is_have_odds' => 1,
                        'money_line_h' => 2.55,
                        'money_line_a' => 2.91,
                        'money_line_d' => 3.22,
                        'spreads_p' => 0,
                        'spreads_h' => 1.961,
                        'spreads_a' => 1.934,
                        'totals_point' => 2.5,
                        'over' => 2.08,
                        'under' => 1.826,
                        'created_at' => '2023-12-11 08:10:07',
                        'updated_at' => '2023-12-11 08:10:07',
                        'status' => 1
                    ],
                        [
                            'id' => 41,
                            'sport_id' => '1',
                            'sport_name' => 'Soccer',
                            'last_call' => '2023-12-11 08:10:01',
                            'event_id' => 1582578117,
                            'league_id' => 2196,
                            'league_name' => 'Spain - La Liga',
                            'starts' => '2023-12-12 03:30:00',
                            'home' => 'Real Madrid',
                            'away' => 'Barcelona h',
                            'event_type' => 'prematch',
                            'is_have_odds' => 1,
                            'money_line_h' => 2.55,
                            'money_line_a' => 2.91,
                            'money_line_d' => 3.22,
                            'spreads_p' => 0,
                            'spreads_h' => 1.961,
                            'spreads_a' => 1.934,
                            'totals_point' => 2.5,
                            'over' => 2.08,
                            'under' => 1.826,
                            'created_at' => '2023-12-11 08:10:07',
                            'updated_at' => '2023-12-11 08:10:07',
                            'status' => 1
                        ],

                        [
                            'id' => 42,
                            'sport_id' => '1',
                            'sport_name' => 'Soccer',
                            'last_call' => '2023-12-11 08:10:01',
                            'event_id' => 1582578118,
                            'league_id' => 2196,
                            'league_name' => 'Spain - La Liga',
                            'starts' => '2023-12-12 03:30:00',
                            'home' => 'Real Madrid',
                            'away' => 'Barcelona i',
                            'event_type' => 'prematch',
                            'is_have_odds' => 1,
                            'money_line_h' => 2.55,
                            'money_line_a' => 2.91,
                            'money_line_d' => 3.22,
                            'spreads_p' => 0,
                            'spreads_h' => 1.961,
                            'spreads_a' => 1.934,
                            'totals_point' => 2.5,
                            'over' => 2.08,
                            'under' => 1.826,
                            'created_at' => '2023-12-11 08:10:07',
                            'updated_at' => '2023-12-11 08:10:07',
                            'status' => 1
                        ],
                            [
                                'id' => 43,
                                'sport_id' => '1',
                                'sport_name' => 'Soccer',
                                'last_call' => '2023-12-11 08:10:01',
                                'event_id' => 1582578119,
                                'league_id' => 2196,
                                'league_name' => 'Spain - La Liga',
                                'starts' => '2023-12-12 03:30:00',
                                'home' => 'Real Madrid',
                                'away' => 'Barcelona j',
                                'event_type' => 'prematch',
                                'is_have_odds' => 1,
                                'money_line_h' => 2.55,
                                'money_line_a' => 2.91,
                                'money_line_d' => 3.22,
                                'spreads_p' => 0,
                                'spreads_h' => 1.961,
                                'spreads_a' => 1.934,
                                'totals_point' => 2.5,
                                'over' => 2.08,
                                'under' => 1.826,
                                'created_at' => '2023-12-11 08:10:07',
                                'updated_at' => '2023-12-11 08:10:07',
                                'status' => 1
                            ],

                            [
                                'id' => 44,
                                'sport_id' => '1',
                                'sport_name' => 'Soccer',
                                'last_call' => '2023-12-11 08:10:01',
                                'event_id' => 1582578120,
                                'league_id' => 2196,
                                'league_name' => 'Spain - La Liga',
                                'starts' => '2023-12-12 03:30:00',
                                'home' => 'Real Madrid',
                                'away' => 'Barcelona k',
                                'event_type' => 'prematch',
                                'is_have_odds' => 1,
                                'money_line_h' => 2.55,
                                'money_line_a' => 2.91,
                                'money_line_d' => 3.22,
                                'spreads_p' => 0,
                                'spreads_h' => 1.961,
                                'spreads_a' => 1.934,
                                'totals_point' => 2.5,
                                'over' => 2.08,
                                'under' => 1.826,
                                'created_at' => '2023-12-11 08:10:07',
                                'updated_at' => '2023-12-11 08:10:07',
                                'status' => 1
                            ],
                                [
                                    'id' => 45,
                                    'sport_id' => '1',
                                    'sport_name' => 'Soccer',
                                    'last_call' => '2023-12-11 08:10:01',
                                    'event_id' => 1582578121,
                                    'league_id' => 2196,
                                    'league_name' => 'Spain - La Liga',
                                    'starts' => '2023-12-12 03:30:00',
                                    'home' => 'Real Madrid',
                                    'away' => 'Barcelona l',
                                    'event_type' => 'prematch',
                                    'is_have_odds' => 1,
                                    'money_line_h' => 2.55,
                                    'money_line_a' => 2.91,
                                    'money_line_d' => 3.22,
                                    'spreads_p' => 0,
                                    'spreads_h' => 1.961,
                                    'spreads_a' => 1.934,
                                    'totals_point' => 2.5,
                                    'over' => 2.08,
                                    'under' => 1.826,
                                    'created_at' => '2023-12-11 08:10:07',
                                    'updated_at' => '2023-12-11 08:10:07',
                                    'status' => 1
                                ],

                                [
                                    'id' => 46,
                                    'sport_id' => '1',
                                    'sport_name' => 'Soccer',
                                    'last_call' => '2023-12-11 08:10:01',
                                    'event_id' => 1582578122,
                                    'league_id' => 2196,
                                    'league_name' => 'Spain - La Liga',
                                    'starts' => '2023-12-12 03:30:00',
                                    'home' => 'Real Madrid',
                                    'away' => 'Barcelona m',
                                    'event_type' => 'prematch',
                                    'is_have_odds' => 1,
                                    'money_line_h' => 2.55,
                                    'money_line_a' => 2.91,
                                    'money_line_d' => 3.22,
                                    'spreads_p' => 0,
                                    'spreads_h' => 1.961,
                                    'spreads_a' => 1.934,
                                    'totals_point' => 2.5,
                                    'over' => 2.08,
                                    'under' => 1.826,
                                    'created_at' => '2023-12-11 08:10:07',
                                    'updated_at' => '2023-12-11 08:10:07',
                                    'status' => 1
                                ]
        ]);
    }
}